- name: "Gather packages information"
  package_facts:
    manager: "auto"

# Verify Hostname
- include: initialize.yml
- include: miscellaneous.yml
- include: scapremediations.yml
- include: user.yml


- name: Cleaning up temp directories used for installs
  import_tasks: cleanup.yml

- name: Aide initialize
  import_tasks: aide.yml
